project_id = "yqvhyqgrjevshlcnhgpz"

[functions.delete-account]
verify_jwt = false

[functions.invite-promoter]
verify_jwt = false

[functions.claim-promoter-link]
verify_jwt = false

[functions.handle-promoter-request]
verify_jwt = false

[functions.claim-ticket]
verify_jwt = false

[functions.approve-organizer-request]
verify_jwt = false

